@url = http://localhost:4000/product
@id = 626448b905786cf2feddfd35

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoiNjI4YjFhNmY5YTAzM2JmMzZiYmNmM2NhIiwibmFtZSI6InRlc3QgYXBpIiwicm9sZSI6InVzZXIifSwiaWF0IjoxNjUzMjg1NjY0LCJleHAiOjE2NTMyODY1NjR9.MVTy9eB6GQhdqecEwCLn7uKfolbV61GMQmM9RhNmWUA

###
# @name allProduct
GET {{url}} HTTP/1.1

###
# @name getProduct
GET {{url}}/{{id}} HTTP/1.1
###

# @name addProduct
POST {{url}} HTTP/1.1
Accept:  application/json
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name": "HP Pavillion",
    "description": "New, 8GB ram, ssd",
    "category": "electronics",
    "price": 150000
}

###
# @name updateProduct
PUT {{url}}/{{id}} HTTP/1.1
Accept:  application/json
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name": "HP Pavillion",
    "description": "New, 8GB ram, ssd",
    "category": "electronics",
    "price": 150000
}

{
    "name": "hp pavillion 14HD",
    "description": "New, 8GB ram, ssd",
    "category": "laptop",
    "price": 350000
}

###
# @name removeProduct
DELETE {{url}}/{{id}} HTTP/1.1

###
GET  {{url}}/name/macbook  HTTP/1.1

###
GET  {{url}}/category/electronics  HTTP/1.1