@url = http://localhost:4000/user

GET {{url}} HTTP/1.1

###

POST {{url}} HTTP/1.1
Accept:  application/json
Content-Type: application/json

{
    "firstname": "samuel",
    "lastname": "fasanya",
    "email": "samuel@gmail.com",
    "password": "samuel78"
}